### ISSUE TITLE
SingleTablePersister issue

### ISSUE THREAD

**Issue by paulstoica** [MediaMonks/symfony-mssql-bundle#4]
I am using your bundle for mssql server support, but we want also to use "single table inheritance" feature from Doctrine, but there is an issue, I found what it is, and I'm asking if it can be fixed in the feature?

The issue is that your bundle overwrite Doctrine\ORM\Persisters\Entity\SingleTablePersister, in different files from "/doctrine/orm/lib/", with MediaMonks\MssqlBundle\Doctrine\ORM\Persisters\Entity\SingleTablePersister, but this class doesn't exists there, so we receive an error. This is done in MediaMonks\MssqlBundle\Composer\ScriptHandler.

So, can this be fixed?

Thank you.
Best regards,
Paul

**Comment by slootjes** [comment]
Since the SingleTablePersister eventually extends the BasicEntityPersister (which works) I think it's a typo in the ScriptHandler. Could you try to rename "SingleTablePersister" there to "JoinedSubclassPersister" and see if it works?

Also, if you receive an error somewhere it's helpful to also put it in this issue.

**Comment by paulstoica** [comment]
It's a vendor package/bundle, so we should not change any code there.
The JoinedSubclassPersister method's "executeInserts" throw an exception "throw new \Exception('Not implemented with UTF8 support yet, implement it or avoid joined subclasses');" so we can't use it.

The error is a simple PHP error.. the class MediaMonks\MssqlBundle\Doctrine\ORM\Persisters\Entity\SingleTablePersister does't not exist(nor the file), and it is used in doctrine ORM classes, like UnitOfWork, because the MediaMonks\MssqlBundle\Composer\ScriptHandler updated the files and replace this class from Doctrine with one from MediaMonks\MssqlBundle.

So, what I'm want to say:  the bundle can be updated in a way that, to create that file/class, or to remove the "SingleTablePersister" from that replacing  array in MediaMonks\MssqlBundle\Composer\ScriptHandler:line:44

Unless this is done, anyone who want to use this package with single table inheritance will not be able.

Thank you for your answer.
Best regards,
Paul

**Comment by paulstoica** [comment]
It woks if I remove the SingleTablePersister from that array

**Comment by slootjes** [comment]
I've updated the package with the replacement of the "SingleTablePersister" class removed, if you update your package with "composer update mediamonks/mssql-bundle" you should be good :) Thanks for reporting this.

**Comment by paulstoica** [comment]
Alright, Thank you very much.

Have a good day.
